feat: add exception logging function, add tests
splunk/addonfactory-solutions-library-python pull request #344
Opened 2024-01-25 21:29 UTC by sgoral-splunk

this feature adds exception logging functionality

2024-01-29 12:14 UTC, artemrys requested changes
This is what I got during my testing:

```
    def stream_events(self, inputs, event_writer):
        for input_name, input_item in inputs.inputs.items():
            normalized_input_name = input_name.split("/")[-1]
            logger = logger_for_input(normalized_input_name)
            try:
                session_key = self._input_definition.metadata["session_key"]
                log_level = conf_manager.get_log_level(
                    logger=logger,
                    session_key=session_key,
                    app_name=ADDON_NAME,
                    conf_name=f"{ADDON_NAME}_settings",
                )
                logger.setLevel(log_level)
                log.modular_input_start(logger, normalized_input_name)
                data = get_data_from_api(logger, "hello world")
                sourcetype = "dummy-data"
                for line in data:
                    event_writer.write_event(
                        smi.Event(
                            data=json.dumps(line, ensure_ascii=False, default=str),
                            index=input_item.get("index"),
                            sourcetype=sourcetype,
                        )
                    )
                raise ValueError("throwing a random exception out of nowhere")
                log.events_ingested(
                    logger, normalized_input_name, sourcetype, len(data)
                )
                log.modular_input_end(logger, normalized_input_name)
            except Exception as e:
                log.log_exception(
                    logger,
                    e,
                    msg_before="Exception raised while ingesting data for ",
                    log_level=logging.ERROR,
                )
```

<img width="1501" alt="image" src="https://github.com/splunk/addonfactory-solutions-library-python/assets/11015487/deac4024-e6b5-4a87-aacd-892e59b3e899">

2024-01-29 12:14 UTC, artemrys commented on solnlib/log.py
> +import sys
`sys` is not being used here.

2024-01-29 12:14 UTC, artemrys commented on solnlib/log.py
> +    log_level: int = logging.INFO,
logging.ERROR might be a better default value for such log?

2024-01-29 13:21 UTC, sgoral-splunk commented on solnlib/log.py
> +import sys
Right, maybe we can add flake8 to pre-commit?

2024-01-29 13:26 UTC, sgoral-splunk commented
that's odd, because it worked for me every time and it looks like this:
<img width="1988" alt="image" src="https://github.com/splunk/addonfactory-solutions-library-python/assets/138458044/84fcf486-68f3-4bd9-a784-812906473185">
I will try to reproduce the error

2024-01-29 16:28 UTC, artemrys commented on solnlib/log.py
> +import sys
Let's do this.

2024-01-30 11:21 UTC, artemrys approved these changes

2024-01-30 11:21 UTC, merged

2024-03-07 14:39 UTC, srv-rr-github-token commented
:tada: This PR is included in version 4.13.0-beta.1 :tada:

The release is available on [GitHub release](https://github.com/splunk/addonfactory-solutions-library-python/releases/tag/v4.13.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-21 11:41 UTC, srv-rr-github-token commented
:tada: This PR is included in version 4.13.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/addonfactory-solutions-library-python/releases/tag/v4.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: